"""The growing, committed failure corpus + the monotone-improvement ratchet.

Every silent-wrong-resolution the flywheel discovers is frozen here as a
regression case. Two artifacts live under ``benchmark/vision_hardening/``:

- ``corpus.json`` — the catalog of known silent-wrong cases (family + fixture
  params + perturbation) plus ``ratchet_max_silent_wrong``, the ceiling the CI
  gate enforces. The number can only be **lowered** (a hardening fix that
  removes silent-wrongs), never raised without an explicit, reviewed decision.
- ``results.json`` — a full measured snapshot (template + OCR tiers, outcome
  breakdown, SWER), regenerated by ``python -m
  openadapt_flow.validation.hardening``.

The corpus is FROZEN like the repo's other validation manifests
(``tests/test_adversary_corpus.py``): a resolver change that flips a known
silent-wrong to safe (the goal) requires regenerating the corpus and lowering
the ratchet in the same reviewed change. That is the flywheel's ratchet — the
silent-wrong rate is mechanically prevented from rising and is expected to fall
release over release.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from openadapt_flow.validation.hardening.harness import (
    Outcome,
    ResultRow,
    summarize,
    sweep,
)

SCHEMA_VERSION = "openadapt.vision-hardening-corpus.v1"


def _repo_root() -> Path:
    # openadapt_flow/validation/hardening/corpus.py -> repo root
    return Path(__file__).resolve().parents[3]


def corpus_path() -> Path:
    return _repo_root() / "benchmark" / "vision_hardening" / "corpus.json"


def results_path() -> Path:
    return _repo_root() / "benchmark" / "vision_hardening" / "results.json"


def _case_key(entry: dict[str, Any]) -> str:
    fp = ",".join(
        f"{k}={entry['fixture_params'][k]}" for k in sorted(entry["fixture_params"])
    )
    pp = ",".join(
        f"{k}={entry['perturbation_params'][k]}"
        for k in sorted(entry["perturbation_params"])
    )
    return f"{entry['family']}({fp})|{entry['perturbation']}({pp})"


def row_key(row: ResultRow) -> str:
    fp = ",".join(f"{k}={row.fixture_params[k]}" for k in sorted(row.fixture_params))
    pp = ",".join(
        f"{k}={row.perturbation_params[k]}" for k in sorted(row.perturbation_params)
    )
    return f"{row.family}({fp})|{row.perturbation}({pp})"


def build_corpus(rows: list[ResultRow]) -> dict[str, Any]:
    """Freeze all silent-wrong rows into a corpus document (sorted, stable)."""
    silent = [r for r in rows if r.outcome is Outcome.SILENT_WRONG]
    entries = sorted((r.corpus_entry() for r in silent), key=_case_key)
    return {
        "schema_version": SCHEMA_VERSION,
        "description": (
            "Frozen catalog of silent-wrong-resolution cases discovered by the "
            "vision hardening flywheel over the TEMPLATE-tier (font-free, "
            "cv2-deterministic) fixture x perturbation sweep. Each case is a "
            "metamorphic violation: a perturbation that preserved the true "
            "target's identity/location still flipped the resolved target onto "
            "a look-alike decoy (or off-target). ratchet_max_silent_wrong is "
            "the CI ceiling -- it may only be LOWERED by a hardening fix."
        ),
        "ratchet_max_silent_wrong": len(entries),
        "silent_wrong_count": len(entries),
        "cases": entries,
    }


def load_corpus() -> dict[str, Any]:
    return json.loads(corpus_path().read_text())


def ratchet_max() -> int:
    return int(load_corpus()["ratchet_max_silent_wrong"])


def corpus_case_keys() -> set[str]:
    return {_case_key(c) for c in load_corpus()["cases"]}


def build_results(
    template_rows: list[ResultRow], ocr_rows: list[ResultRow] | None
) -> dict[str, Any]:
    """A full measured snapshot for ``results.json`` (template + OCR tiers)."""
    template = summarize(template_rows)
    doc: dict[str, Any] = {
        "schema_version": "openadapt.vision-hardening-results.v1",
        "caveat": (
            "Measured on synthetic real-glyph/real-shape fixtures with the REAL "
            "resolver + REAL vision (cv2 template matcher + RapidOCR), NOT on a "
            "live RDP/Citrix/HDX frame. It measures the resolution ladder's "
            "silent-mis-resolution (SWER) under a metamorphic perturbation "
            "space; it does not raise any substrate's maturity claim. The "
            "TEMPLATE tier is font-free and cv2-deterministic (the CI ratchet); "
            "the OCR tier depends on the OCR engine/platform and is "
            "informational."
        ),
        "template_tier": {
            "gated_in_ci": True,
            **template.as_dict(),
        },
    }
    if ocr_rows is not None:
        doc["ocr_tier"] = {
            "gated_in_ci": False,
            "note": (
                "RapidOCR-dependent; counts can vary across OCR-engine/font "
                "versions, so this tier is reported, not hard-gated per PR."
            ),
            **summarize(ocr_rows).as_dict(),
        }
    return doc


def regenerate(*, include_ocr: bool = True) -> tuple[dict[str, Any], dict[str, Any]]:
    """Re-run the sweep and rebuild both artifacts (does not write them)."""
    from openadapt_flow.validation.hardening import fixtures as fx

    template_rows = sweep(include_ocr=False)
    ocr_rows = None
    if include_ocr and fx.ocr_available():
        # Full sweep includes OCR fixtures; slice them back out for the tier.
        all_rows = sweep(include_ocr=True)
        template_families = {"repeated_icons", "form_fields"}
        ocr_rows = [r for r in all_rows if r.family not in template_families]
    corpus = build_corpus(template_rows)
    results = build_results(template_rows, ocr_rows)
    return corpus, results
