"""Generated by openadapt-flow. Human-readable rendering of
workflow 'mockmed-triage' — for code review only; the replayer
executes workflow.json, not this file."""

WORKFLOW_NAME = 'mockmed-triage'
RECORDING_ID = '18088720baa347c9b6fae136362ddfa0'
PARAMS = {'note': 'Showcase triage booking three months'}  # param -> example/default value


def run(flow, params=PARAMS):
    # step_000: click at (214, 195) [reversible]
    # landmark: 'Sign in to MockMed' (above, 131px)
    # landmark: 'Username' (left_of, 132px)
    flow.click(template='templates/step_000.png', click_point=(214, 195), region=(134, 163, 160, 64))
    # expect region_stable region=(17, 145, 394, 100) phash='e01fe01f2f1f85e0' (tol 16)

    # step_001: type 'nurse.demo' [reversible]
    flow.type_text('nurse.demo')
    # expect region_stable region=(27, 156, 147, 77) phash='c2c969c3d23eb436' (tol 16)
    # expect text_present text='nurse.demo'

    # step_002: click at (214, 264) [reversible]
    # landmark: 'Sign In' (left_of, 112px)
    # landmark: 'nurse.demo' (left_of, 132px)
    flow.click(template='templates/step_002.png', click_point=(214, 264), region=(134, 232, 160, 64))
    # expect region_stable region=(17, 214, 394, 100) phash='e0f0e01f3f0f95c2' (tol 16)

    # step_003: type 'mockmed-demo-pass' [reversible]
    flow.type_text('mockmed-demo-pass')
    # expect region_stable region=(27, 229, 158, 69) phash='c0c9cdc9dec0f836' (tol 16)

    # step_004: click 'Sign In' [reversible]
    # landmark: 'Password' (above, 95px)
    # landmark: 'nurse.demo' (above, 130px)
    flow.click(template='templates/step_004.png', click_point=(119, 324), region=(39, 292, 160, 64), ocr_text='Sign In')
    # expect region_stable region=(0, 87, 968, 314) phash='f7f138e0e868e468' (tol 16)
    # expect text_present text='Cardiology follow-up'

    # step_005: click 'Open' [reversible]
    # landmark: 'Action' (above, 51px)
    # landmark: 'Open' (below, 58px)
    flow.click(template='templates/step_005.png', click_point=(775, 186), region=(695, 154, 160, 64), ocr_text='Open')
    # expect region_stable region=(0, 43, 968, 318) phash='f8e083ffbc08383c' (tol 16)
    # expect text_present text='JaneSample—MRNP1—DOB1980-01-01'

    # step_006: click 'New Encounter' [reversible]
    # landmark: 'Encounters' (below, 61px)
    # landmark: 'No encountersyet.' (below, 85px)
    flow.click(template='templates/step_006.png', click_point=(114, 159), region=(34, 127, 160, 64), ocr_text='New Encounter')
    # expect region_stable region=(0, 170, 696, 215) phash='ff77c16a62c0e2c0' (tol 16)
    # expect text_present text='EncounterType'

    # step_007: click 'Triage' [reversible]
    # landmark: 'Note' (below, 70px)
    # landmark: 'NewEncounter' (above, 76px)
    flow.click(template='templates/step_007.png', click_point=(85, 160), region=(5, 128, 160, 64), ocr_text='Triage')
    # expect region_stable region=(0, 109, 177, 102) phash='88c2f2295d2da73d' (tol 16)

    # step_008: click at (344, 290) [reversible]
    # landmark: 'Consult' (left_of, 189px)
    # landmark: 'Save Encounter' (left_of, 233px)
    flow.click(template='templates/step_008.png', click_point=(344, 290), region=(184, 226, 320, 128))
    # expect region_stable region=(0, 195, 696, 190) phash='ff3fd53f6a002a00' (tol 16)

    # step_009: type <note> [reversible]
    flow.type_text(params['note'])
    # expect region_stable region=(2, 206, 408, 79) phash='f0f07e7cd12b2b80' (tol 16)

    # step_010: click 'Save Encounter' [reversible]
    # landmark: 'Showcase triage booking three months' (above, 162px)
    # landmark: 'Note' (above, 199px)
    flow.click(template='templates/step_010.png', click_point=(134, 391), region=(54, 359, 160, 64), ocr_text='Save Encounter')
    # expect region_stable region=(0, 43, 968, 169) phash='e633398c19336673' (tol 16)
    # expect text_present text='JaneSample—MRNP1—DOB1980-01-01'
