"""Generated by openadapt-flow. Human-readable rendering of
workflow 'openemr-showcase' — for code review only; the replayer
executes workflow.json, not this file."""

WORKFLOW_NAME = 'openemr-showcase'
RECORDING_ID = '50758ec282e94c4a9f99f69ab7415678'
PARAMS = {'note': 'Reviewed hypertension follow-up; BP within target range today.'}  # param -> example/default value


def run(flow, params=PARAMS):
    # step_000: click 'ername' [reversible]
    # landmark: 'PracticeManagementsolution.' (left_of, 82px)
    # landmark: 'Password' (left_of, 86px)
    flow.click(template='templates/step_000.png', click_point=(705, 404), region=(625, 372, 160, 64), ocr_text='ername')
    # expect region_stable region=(555, 351, 301, 106) phash='c3dbd8dac3d098d0' (tol 16)

    # step_001: type 'admin' [reversible]
    flow.type_text('admin')
    # expect region_stable region=(570, 365, 138, 77) phash='ce7cb37ccc78b040' (tol 16)
    # expect text_present text='admin'

    # step_002: click 'Password' [reversible]
    # landmark: 'Default-English(Standard)' (below, 56px)
    # landmark: 'admin' (left_of, 80px)
    flow.click(template='templates/step_002.png', click_point=(684, 458), region=(604, 426, 160, 64), ocr_text='Password')
    # expect region_stable region=(555, 351, 301, 160) phash='c14adac6dacae1d8' (tol 16)

    # step_003: type 'pass' [reversible]
    flow.type_text('pass')
    # expect region_stable region=(571, 419, 133, 77) phash='a27f9178c7c79038' (tol 16)

    # step_004: click 'Login' [reversible]
    # landmark: 'Acknowledgments,Licensing and Certification' (below, 45px)
    # landmark: 'Default-English(Standard)' (right_of, 89px)
    flow.click(template='templates/step_004.png', click_point=(639, 566), region=(559, 534, 160, 64), ocr_text='Login')
    # expect text_present text='CalendarFinderFlowRecallsMessagesPatientFeesModulesInventoryProceduresAdminReportsMiscellaneousPopups'

    # step_005: click 'Searchbyanydemogre' [reversible]
    # landmark: 'Week' (below, 172px)
    # landmark: 'Billy Smith' (left_of, 353px)
    # identity: armed via PHI-free salted-hash template (2 band tokens); no patient identifier stored
    flow.click(template='templates/step_005.png', click_point=(1121, 31), region=(1041, 0, 160, 64), ocr_text='Searchbyanydemogre')
    # expect region_stable region=(286, 531, 994, 84) phash='fff881038670f07c' (tol 16)

    # step_006: type 'Phil' [reversible]
    flow.type_text('Phil')
    # expect region_stable region=(1017, 0, 209, 71) phash='eae01715fb7a801d' (tol 16)
    # expect text_present text='Phil'

    # step_007: press Enter [reversible]
    flow.press('Enter')
    # expect region_stable region=(0, 72, 1280, 728) phash='fbf70460c387a568' (tol 16)
    # expect text_present text='beninNewBrowserTabSearchwithexactmethod'

    # step_008: click 'ford,Phil' [reversible]
    # landmark: 'Name' (above, 45px)
    # landmark: 'earchbyName' (above, 104px)
    # identity: armed via PHI-free salted-hash template (4 band tokens); no patient identifier stored
    flow.click(template='templates/step_008.png', click_point=(17, 443), region=(0, 411, 160, 64), ocr_text='ford,Phil')
    # expect region_stable region=(0, 195, 1280, 326) phash='fee1e1a6b28180db' (tol 16)
    # expect text_present text='edicalRecordDashboard-PhilBelford'

    # step_009: scroll by (0, 400) [reversible]
    flow.scroll(0, 400)

    # step_010: scroll by (0, 400) [reversible]
    flow.scroll(0, 400)

    # step_011: scroll by (0, 400) [reversible]
    flow.scroll(0, 400)

    # step_012: scroll by (0, 400) [reversible]
    flow.scroll(0, 400)

    # step_013: click at (815, 369) [reversible]
    # landmark: 'None' (right_of, 123px)
    # landmark: 'Immunizations' (above, 180px)
    flow.click(template='templates/step_013.png', click_point=(815, 369), region=(735, 337, 160, 64))
    # expect region_stable region=(0, 176, 691, 174) phash='c3da3fb5b7408590' (tol 16)
    # expect text_present text='PatientMessagesforBelford,Phil'

    # step_014: click '+Add <B' [irreversible]
    # landmark: 'Show All' (below, 98px)
    # landmark: 'alendarx' (above, 102px)
    # identity: armed via PHI-free salted-hash template (4 band tokens); no patient identifier stored
    flow.click(template='templates/step_014.png', click_point=(90, 281), region=(10, 249, 160, 64), ocr_text='+Add <B')
    # expect region_stable region=(0, 0, 1280, 800) phash='c6e62f272d9090ed' (tol 16)
    # expect text_present text='Calendar Finder Flow Recalls Messa'

    # step_015: click at (639, 357) [reversible]
    # landmark: 'Save as new message' (left_of, 169px)
    # landmark: 'Smith, Billy' (left_of, 216px)
    flow.click(template='templates/step_015.png', click_point=(639, 357), region=(479, 293, 320, 128))
    # expect region_stable region=(351, 269, 578, 178) phash='e8d0c0f0f8f87a6a' (tol 16)

    # step_016: type <note> [reversible]
    flow.type_text(params['note'])

    # step_017: click 'Save as new messag' [irreversible]
    # landmark: 'Smith, Billy' (above, 191px)
    # landmark: 'Active' (left_of, 234px)
    flow.click(template='templates/step_017.png', click_point=(489, 452), region=(409, 420, 160, 64), ocr_text='Save as new messag')
    # expect region_stable region=(0, 0, 1280, 800) phash='c0d91b9db162c6a7' (tol 16)
    # expect text_present text='CalendarFinderFlowRecallsMessagesPatientFeesModulesInventoryProceduresAdminReportsMiscellaneousPopups'
