# SPDX-License-Identifier: AGPL-3.0-only
# Adapted by OpenAdapt.AI on 2026-07-17.
# Source: https://github.com/openimis/openimis-dist_dkr/blob/cd6220d1f0578e56a589c47953250c2ad3d0caa5/conf/nginx/variables/var.conf
# Full license: ../LICENSE-AGPL-3.0.md

set $backend "backend:8000";
set $opensearch "opensearch-dashboards:5601";
set $lightning "lightning:4000";
set $frontend "lightning:4000";
