"""Emit a workflow bundle as a standalone MCP server (``server.py``).

The generated source exposes the workflow as a single FastMCP tool with
typed parameters. Generation is pure string templating: this module never
imports ``mcp`` — the generated file does, at *its* runtime.

The workflow bundle is COPIED next to the generated file (as ``bundle/``)
and referenced relative to ``__file__``, so the emitted directory is
self-contained and portable across machines.
"""

from __future__ import annotations

import ast
import re
import shutil
from pathlib import Path

from openadapt_flow.ir import Workflow

_BUNDLE_SUBDIR = "bundle"

_SERVER_TEMPLATE = '''\
"""MCP server exposing the {name!r} workflow as a tool.

Generated by openadapt-flow. Requires: mcp, playwright, openadapt-flow.
The workflow bundle lives alongside this file in ./{bundle_subdir}/.
Run with: python {out_name}
"""

from __future__ import annotations

import tempfile
from pathlib import Path

from mcp.server.fastmcp import FastMCP

BUNDLE_DIR = Path(__file__).resolve().parent / {bundle_subdir!r}

mcp = FastMCP({name!r})


@mcp.tool()
def {func_name}(url: str{param_sig}) -> dict:
    """{docstring}

    Args:
        url: URL of the running target application.
{param_docs}
    Returns:
        Dict with success flag, run directory, heal count, and total ms.
    """
    from playwright.sync_api import sync_playwright

    from openadapt_flow.backends.playwright_backend import PlaywrightBackend
    from openadapt_flow.ir import Workflow
    from openadapt_flow.runtime import Replayer

    workflow = Workflow.load(BUNDLE_DIR)
    params = {params_dict}
    run_dir = Path(tempfile.mkdtemp(prefix="openadapt_flow_run_"))
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page(viewport={{"width": 1280, "height": 800}})
        page.goto(url)
        try:
            backend = PlaywrightBackend(page)
            report = Replayer(backend).run(
                workflow,
                params=params,
                bundle_dir=BUNDLE_DIR,
                run_dir=run_dir,
            )
        finally:
            browser.close()
    return {{
        "success": report.success,
        "run_dir": str(run_dir),
        "heal_count": report.heal_count,
        "model_calls": report.model_calls,
        "total_ms": report.total_ms,
    }}


if __name__ == "__main__":
    mcp.run()
'''


def _identifier(name: str) -> str:
    """Coerce an arbitrary name into a valid Python identifier."""
    ident = re.sub(r"[^0-9a-zA-Z_]+", "_", name).strip("_").lower()
    if not ident:
        ident = "workflow"
    if ident[0].isdigit():
        ident = f"w_{ident}"
    return ident


def _clean_line(text: str) -> str:
    """Make text safe to embed inside a generated docstring."""
    return text.replace("\\", " ").replace('"""', "'''").replace("\n", " ")


def emit_mcp_server(bundle_dir: Path | str, out_path: Path | str) -> Path:
    """Generate a standalone, portable FastMCP ``server.py`` for the bundle.

    The generated module defines one tool named after the workflow, with a
    required ``url`` argument plus one typed ``str`` argument per workflow
    parameter (defaulting to the recorded example value). The source is
    validated with :func:`ast.parse` before being written. The workflow
    bundle is copied to ``<out_path's directory>/bundle/`` and referenced
    relative to the generated file, so the directory can be shipped as-is.

    Args:
        bundle_dir: Workflow bundle directory (contains ``workflow.json``).
        out_path: Destination path for the generated ``server.py``.

    Returns:
        Path to the written server source file.
    """
    bundle = Path(bundle_dir).resolve()
    workflow = Workflow.load(bundle)
    out = Path(out_path)

    func_name = f"run_{_identifier(workflow.name)}"
    param_names = {name: _identifier(name) for name in workflow.params}

    param_sig = "".join(
        f", {ident}: str = {workflow.params[name]!r}"
        for name, ident in param_names.items()
    )
    if param_names:
        params_dict = (
            "{"
            + ", ".join(f"{name!r}: {ident}" for name, ident in param_names.items())
            + "}"
        )
        param_docs = "".join(
            f"        {ident}: Value for the {_clean_line(name)!r} "
            f"workflow parameter.\n"
            for name, ident in param_names.items()
        )
    else:
        params_dict = "{}"
        param_docs = ""

    docstring = _clean_line(
        f"Replay the {workflow.name!r} workflow "
        f"({len(workflow.steps)} steps) against a live app."
    )

    source = _SERVER_TEMPLATE.format(
        name=workflow.name,
        out_name=out.name,
        bundle_subdir=_BUNDLE_SUBDIR,
        func_name=func_name,
        param_sig=param_sig,
        param_docs=param_docs,
        params_dict=params_dict,
        docstring=docstring,
    )

    # Guarantee the emitted source is syntactically valid Python.
    ast.parse(source)

    out.parent.mkdir(parents=True, exist_ok=True)
    bundle_copy = out.parent / _BUNDLE_SUBDIR
    if bundle_copy.resolve() != bundle:
        shutil.copytree(bundle, bundle_copy, dirs_exist_ok=True)
    out.write_text(source, encoding="utf-8")
    return out
