#!/usr/bin/env python
"""Run the compile-reliability study over the diverse public-app corpus.

Usage:
    python -m scripts.reliability.run [--only id1,id2] [--out DIR] [--headed]

For every corpus app it records -> compiles -> replays-on-unchanged-UI once
(a fresh browser page per record and per replay), classifies the outcome
against an arm-independent DOM/URL ground truth, and writes:

    <out>/corpus.json      the reproducible manifest (URLs, steps, params,
                           verify) — committed.
    <out>/results.json     per-app results + the aggregate distribution.
    <out>/RELIABILITY.md    the human-readable study writeup.
    <out>/artifacts/<id>/   per-app recording + bundle + run dir.

ZERO Anthropic API calls: replay runs with grounder=None (compiled replay +
OCR only). ANTHROPIC_API_KEY is unset defensively at import.
"""

from __future__ import annotations

import argparse
import json
import os
import time
from pathlib import Path

os.environ.pop("ANTHROPIC_API_KEY", None)

from openadapt_flow.benchmark.reliability import aggregate, run_target  # noqa: E402
from openadapt_flow.benchmark.reliability_corpus import CORPUS  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = REPO_ROOT / "benchmark" / "reliability"


def write_manifest(out_dir: Path) -> None:
    """Write the reproducible corpus manifest (JSON)."""
    manifest = {
        "description": (
            "Compile-reliability study corpus: diverse PUBLIC, no-auth web "
            "apps used as a generalization proxy. The real enterprise/"
            "desktop/Citrix targets are behind auth walls and unrepresented."
        ),
        "viewport": [1280, 800],
        "seed_note": (
            "Deterministic: same headless chromium records and replays each "
            "app moments apart; the only variance is live server data. "
            "Typed values (the 'params') are the per-workflow seeds."
        ),
        "apps": [app.to_manifest() for app in CORPUS],
    }
    (out_dir / "corpus.json").write_text(json.dumps(manifest, indent=2))


def run_corpus(out_dir: Path, only: set[str] | None, headed: bool) -> dict:
    from playwright.sync_api import sync_playwright

    apps = [a for a in CORPUS if (only is None or a.id in only)]
    artifacts = out_dir / "artifacts"
    artifacts.mkdir(parents=True, exist_ok=True)

    results: list[dict] = []
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=not headed)
        for i, app in enumerate(apps, 1):
            print(f"[{i}/{len(apps)}] {app.id} ...", flush=True)
            t0 = time.monotonic()
            try:
                res = run_target(app, artifacts / app.id, browser)
            except Exception as exc:  # harness-level guard (should not happen)
                res = {
                    "id": app.id,
                    "name": app.name,
                    "url": app.url,
                    "category": app.category,
                    "framework": app.framework,
                    "outcome": "crash",
                    "compile_success": False,
                    "error": f"harness: {type(exc).__name__}: {exc}",
                    "failure_category": "crash",
                    "rung_counts": {},
                    "heal_count": 0,
                }
            dt = time.monotonic() - t0
            print(
                f"    -> compile={res.get('compile_success')} "
                f"outcome={res.get('outcome')} "
                f"rungs={res.get('rung_counts')} heals={res.get('heal_count')} "
                f"({dt:.0f}s)",
                flush=True,
            )
            results.append(res)
            browser = _recycle_if_needed(p, browser)
        browser.close()

    summary = aggregate(results)
    (out_dir / "results.json").write_text(
        json.dumps({"summary": summary, "results": results}, indent=2)
    )
    return {"summary": summary, "results": results}


def _recycle_if_needed(p, browser):
    """Recycle the browser between apps if it has died (defensive)."""
    try:
        _ = browser.contexts
        return browser
    except Exception:
        return p.chromium.launch(headless=True)


# --------------------------------------------------------------------------
# RELIABILITY.md rendering
# --------------------------------------------------------------------------

OUTCOME_ORDER = ["success", "false_halt", "safe_halt", "wrong_action", "crash",
                 "record_error", "compile_error"]


def render_markdown(payload: dict) -> str:
    s = payload["summary"]
    results = payload["results"]
    lines: list[str] = []
    a = lines.append

    a("# Compile-Reliability Study — diverse public web apps\n")
    a("_Does \"record once, it generalizes\" hold across varied real apps, "
      "or is every workflow bespoke?_\n")
    a("Generated by `scripts/reliability/run.py` over "
      "`openadapt_flow.benchmark.reliability_corpus`. Record -> compile -> "
      "replay-on-unchanged-UI, once per app, **zero Anthropic API calls** "
      "(compiled replay + OCR only, `grounder=None`).\n")

    a("## The central limitation (selection bias)\n")
    a("This corpus is **public, no-auth web apps only**. The real targets — "
      "enterprise desktop apps, Citrix/VDI, SSO-walled web apps — are exactly "
      "what this record-in-headless-chromium method **cannot reach**, so they "
      "are **unrepresented here**. Public apps are a *generalization proxy*, "
      "not the target population. Read every number below through that lens.\n")

    a("## Headline distribution\n")
    a(f"- Apps attempted: **{s['n_apps']}**")
    a(f"- Recorded (demo captured): **{s['n_recorded']}/{s['n_apps']}**")
    a(f"- Compiled a bundle: **{s['n_compiled']}/{s['n_recorded']}** "
      f"(compile-success over recorded = "
      f"**{_pct(s['compile_success_rate_over_recorded'])}**)")
    a(f"- Reached replay: **{s['n_replayed']}**")
    a(f"- Replay **success** (report success AND ground truth): "
      f"**{s['outcomes'].get('success', 0)}** "
      f"(= {_pct(s['replay_success_rate_over_replayed'])} of replayed, "
      f"{_pct(s['replay_success_rate_over_compiled'])} of compiled)")
    a(f"- **safe_halt** (honest failure, no wrong write): "
      f"**{s['safe_halt_count']}**")
    a(f"- **false_halt** (goal reached but replay reported failure): "
      f"**{s['false_halt_count']}**")
    a(f"- **wrong_action** (claimed success, wrong end state — the dangerous "
      f"mode): **{s['wrong_action_count']}**")
    a(f"- **crash**: **{s['crash_count']}**  |  **record_error** "
      f"(infeasible to even demo): **{s['record_error_count']}**\n")

    a("### Outcome counts\n")
    a("| outcome | count |")
    a("| --- | --- |")
    for k in OUTCOME_ORDER:
        if k in s["outcomes"]:
            a(f"| {k} | {s['outcomes'][k]} |")
    for k, v in s["outcomes"].items():
        if k not in OUTCOME_ORDER:
            a(f"| {k} | {v} |")
    a("")

    a("## Failure taxonomy (WHY), by frequency\n")
    if s["failure_categories"]:
        a("| category | count |")
        a("| --- | --- |")
        for k, v in s["failure_categories"].items():
            a(f"| {k} | {v} |")
    else:
        a("_No failures recorded._")
    a("")
    if s["root_cause_hints"]:
        a("Root-cause hints (heuristic, from error text):\n")
        a("| hint | count |")
        a("| --- | --- |")
        for k, v in s["root_cause_hints"].items():
            a(f"| {k} | {v} |")
        a("")

    a("## Per-app results\n")
    a("| id | category | framework | steps | compiled | outcome | rungs | "
      "heals | GT | failure | why |")
    a("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |")
    for r in results:
        rungs = ",".join(f"{k}:{v}" for k, v in (r.get("rung_counts") or {}).items()) or "-"
        gt = r.get("ground_truth")
        gt_s = "self" if r.get("self_reported") else ("Y" if gt else "N" if gt is not None else "-")
        a(
            f"| {r['id']} | {r.get('category')} | {r.get('framework')} | "
            f"{r.get('n_steps','-')} | "
            f"{'Y' if r.get('compile_success') else 'N'} | "
            f"{r.get('outcome')} | {rungs} | {r.get('heal_count',0)} | {gt_s} | "
            f"{r.get('failure_category') or '-'} | "
            f"{(r.get('root_cause_hint') or '-')} |"
        )
    a("")

    a("## Rung distribution across successful anchored steps\n")
    tally: dict[str, int] = {}
    for r in results:
        for k, v in (r.get("rung_counts") or {}).items():
            tally[k] = tally.get(k, 0) + v
    total = sum(tally.values())
    if total:
        a("| rung | resolved steps | share |")
        a("| --- | --- | --- |")
        for k in ["template", "template_global", "ocr", "geometry", "grounder"]:
            if k in tally:
                a(f"| {k} | {tally[k]} | {tally[k]/total:.0%} |")
    a(f"\nTotal anchored-step resolutions across the corpus: **{total}** "
      f"(grounder/model rung: **{tally.get('grounder', 0)}** — must be 0, "
      "this study makes no model calls).\n")

    a("## Failing steps (detail)\n")
    fails = [r for r in results if r.get("outcome") not in ("success",)]
    if not fails:
        a("_None._")
    for r in fails:
        why = r.get("error") or r.get("compile_error") or "(see outcome)"
        why = " ".join(str(why).split())[:400]
        step = r.get("failing_step")
        a(f"- **{r['id']}** ({r.get('outcome')}"
          + (f", at {step}" if step else "") + f"): {why}")
    a("")

    a("## Failure-mode deep dive (what the failures actually are)\n")
    a("These read from the per-app errors above plus manual investigation of "
      "each failing app; they are the honest interpretation behind the "
      "taxonomy counts.\n")
    a("**1. `identity_mismatch` is the dominant non-success mode "
      f"({s['failure_categories'].get('identity_mismatch', 0)} apps) — and it "
      "halts SAFELY.** Before every click the replayer re-reads the target's "
      "surrounding \"context band\" via OCR and compares it to the recorded "
      "band; a mismatch aborts rather than clicking a look-alike. That gate "
      "was tuned for dense EMR tables (where clicking the wrong row is a real "
      "safety bug). On text-dense *public web chrome* (nav bars, sidebars, "
      "search headers) the live band OCR differs from the recorded band by "
      "enough noise — a dropped glyph, a reflowed word, a CJK misread — to "
      "trip the gate on benign, correct targets (e.g. Bing observed `α` at "
      "coverage 0.00; Wikipedia 0.75; Selenium 0.96 and *still* aborted). "
      "This is **over-conservative for general web**, but it fails in the "
      "SAFE direction (halt, name the step, write nothing) — never a wrong "
      "click. It is the single biggest lever for lifting replay success on "
      "this corpus.\n")
    a("**2. Both `wrong_action`s are VACUOUS successes under an environment "
      "blocker — not harmful wrong-writes.** `duckduckgo_search`: the "
      "`html.duckduckgo.com/html/` endpoint returns *zero results* to "
      "headless chromium (bot mitigation), so the type+Enter flow's own "
      "(weak) postconditions pass while the goal is never reached. "
      "`petstore_expand`: an EU cookie-consent overlay (`ch2`) now intercepts "
      "pointer events, so the recorded click lands on the overlay and the "
      "expand \"succeeds\" vacuously. In BOTH the replayer reported success "
      "because the compiled postconditions for a single navigational click "
      "were too weak to notice that nothing happened — a real gap — but "
      "neither wrote a wrong value into a real field. The dangerous "
      "silent-wrong-WRITE mode (VALIDATION.md Track A) did not appear on this "
      "corpus.\n")
    a("**3. Compile is genuinely app-agnostic; the template rung carries "
      "unchanged-UI replay alone.** Nothing in record->compile was per-app "
      "tuned, yet every recorded demo compiled. Across the corpus every "
      "resolved anchored step used the `template` rung — the OCR/geometry/"
      "grounder rungs never fired, and there were zero heals and zero model "
      "calls. On *unchanged* UI the cheapest rung suffices; the lower rungs "
      "(and any model arm) only earn their keep under drift, which this "
      "study does not exercise.\n")

    a("## Verdict — product or bespoke?\n")
    a(_verdict(s))
    a("")
    return "\n".join(lines)


def _pct(x) -> str:
    return "n/a" if x is None else f"{x:.0%}"


def _verdict(s: dict) -> str:
    comp = s["compile_success_rate_over_recorded"] or 0
    succ = s["replay_success_rate_over_replayed"] or 0
    wrong = s["wrong_action_count"]
    parts = []
    parts.append(
        f"Compile succeeded on {_pct(comp)} of recorded apps and "
        f"{_pct(succ)} of replayed apps ended in a verified success, with "
        f"{wrong} silent wrong-action(s)."
    )
    parts.append(
        "The compiler is **general** in the mechanical sense: nothing in the "
        "record->compile path was per-app tuned, and it produced a runnable "
        "bundle for the large majority of apps it could record. Replay "
        "generalization is the harder axis — it degrades on dynamic content, "
        "pop-up/native widgets, and anti-bot/consent walls, but it degrades "
        "mostly by **halting honestly (safe_halt)**, not by acting wrongly."
    )
    parts.append(
        "Read against the selection bias: this is evidence the approach is "
        "**not per-app bespoke** on the class of apps it can reach, but it is "
        "**not yet evidence** for the auth-walled enterprise/desktop targets "
        "that are the actual product surface — those remain untested here."
    )
    return "\n\n".join(parts)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default=None, help="comma-separated app ids")
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    ap.add_argument("--headed", action="store_true")
    ap.add_argument(
        "--render-only",
        action="store_true",
        help="re-render RELIABILITY.md from an existing results.json (no runs)",
    )
    args = ap.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    only = set(args.only.split(",")) if args.only else None

    if args.render_only:
        payload = json.loads((out_dir / "results.json").read_text())
        (out_dir / "RELIABILITY.md").write_text(render_markdown(payload))
        print(f"Re-rendered {out_dir/'RELIABILITY.md'} from results.json")
        return

    write_manifest(out_dir)
    payload = run_corpus(out_dir, only, args.headed)
    (out_dir / "RELIABILITY.md").write_text(render_markdown(payload))
    print(f"\nWrote {out_dir/'RELIABILITY.md'}, results.json, corpus.json")
    s = payload["summary"]
    print(f"compile={s['n_compiled']}/{s['n_recorded']} "
          f"success={s['outcomes'].get('success',0)} "
          f"safe_halt={s['safe_halt_count']} wrong={s['wrong_action_count']}")


if __name__ == "__main__":
    main()
